// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © lalo_512

//@version=6
indicator("ORB Zone [ATX Lalo]", "ORB", overlay = true)

// --------- [ ORB ] --------- 
inputMax = input(15, title= "ORB total time (minutes)", group = 'ORB Session')
sess = input.session("0930-0945", "Session Time", group = 'ORB Session')
t = time(timeframe.period, sess + ":1234567")
hide = timeframe.isintraday and timeframe.multiplier <= inputMax

is_newbar(res) => ta.change(time(res)) != 0
in_session = not na(t)
is_first = in_session and not in_session[1]

orb_high = float(na)
orb_low = float(na)

if is_first
    orb_high := high
    orb_low := low
else
    orb_high := orb_high[1]
    orb_low := orb_low[1]
if high > orb_high and in_session
    orb_high := high
if low < orb_low and in_session
    orb_low := low

orbHighColor = orb_high[1] != orb_high ? na : color.blue
orbLowColor = orb_low[1] != orb_low ? na : color.blue

orbPlotHigh = plot(hide ? orb_high : na , style=plot.style_line, color=orbHighColor, title="ORB High", linewidth=2)
orbPlotLow = plot(hide ? orb_low : na , style=plot.style_line, color=orbLowColor, title="ORB Low", linewidth=2)
fill(orbPlotHigh, orbPlotLow, title = 'ORB Background', color = color.new(color.blue, 90))
